// GENERATED by scripts/generate-hole-bearings.mjs on 2026-07-12 — do not
// hand-edit; re-run the script. OSM golf=hole data © OpenStreetMap
// contributors, ODbL. Manual courses (Lincoln Park) live in
// course-holes.ts, not here.

export type HoleSegment = { bearingDeg: number; lengthYd: number };

export type HoleData = {
  hole: number;
  /** Straight tee→green bearing, degrees clockwise from true north. */
  bearingDeg: number;
  par: number | null;
  lengthYd: number | null;
  /** Present for doglegs: tee→corner(s)→green legs in play order. */
  segments?: HoleSegment[];
};

export type CourseHoleData = {
  key: string;
  name: string;
  /** Matched (normalized) against the free-text TeeTime.course field. */
  aliases: string[];
  holes: HoleData[];
};

export const GENERATED_COURSES: CourseHoleData[] = [
  {
    "key": "kings-walk",
    "name": "King's Walk",
    "aliases": [
      "kings walk"
    ],
    "holes": [
      {
        "hole": 1,
        "bearingDeg": 157,
        "par": 4,
        "lengthYd": 395
      },
      {
        "hole": 2,
        "bearingDeg": 153,
        "par": 4,
        "lengthYd": 425
      },
      {
        "hole": 3,
        "bearingDeg": 274,
        "par": 5,
        "lengthYd": 543,
        "segments": [
          {
            "bearingDeg": 281,
            "lengthYd": 361
          },
          {
            "bearingDeg": 261,
            "lengthYd": 182
          }
        ]
      },
      {
        "hole": 4,
        "bearingDeg": 5,
        "par": 3,
        "lengthYd": 174
      },
      {
        "hole": 5,
        "bearingDeg": 106,
        "par": 4,
        "lengthYd": 428
      },
      {
        "hole": 6,
        "bearingDeg": 58,
        "par": 4,
        "lengthYd": 433
      },
      {
        "hole": 7,
        "bearingDeg": 236,
        "par": 4,
        "lengthYd": 403
      },
      {
        "hole": 8,
        "bearingDeg": 352,
        "par": 3,
        "lengthYd": 212
      },
      {
        "hole": 9,
        "bearingDeg": 343,
        "par": 5,
        "lengthYd": 554
      },
      {
        "hole": 10,
        "bearingDeg": 100,
        "par": 4,
        "lengthYd": 408
      },
      {
        "hole": 11,
        "bearingDeg": 114,
        "par": 4,
        "lengthYd": 427,
        "segments": [
          {
            "bearingDeg": 109,
            "lengthYd": 284
          },
          {
            "bearingDeg": 124,
            "lengthYd": 143
          }
        ]
      },
      {
        "hole": 12,
        "bearingDeg": 215,
        "par": 4,
        "lengthYd": 421,
        "segments": [
          {
            "bearingDeg": 205,
            "lengthYd": 267
          },
          {
            "bearingDeg": 232,
            "lengthYd": 154
          }
        ]
      },
      {
        "hole": 13,
        "bearingDeg": 249,
        "par": 3,
        "lengthYd": 202
      },
      {
        "hole": 14,
        "bearingDeg": 52,
        "par": 5,
        "lengthYd": 578,
        "segments": [
          {
            "bearingDeg": 59,
            "lengthYd": 375
          },
          {
            "bearingDeg": 40,
            "lengthYd": 203
          }
        ]
      },
      {
        "hole": 15,
        "bearingDeg": 237,
        "par": 4,
        "lengthYd": 458
      },
      {
        "hole": 16,
        "bearingDeg": 351,
        "par": 3,
        "lengthYd": 192
      },
      {
        "hole": 17,
        "bearingDeg": 75,
        "par": 4,
        "lengthYd": 376,
        "segments": [
          {
            "bearingDeg": 82,
            "lengthYd": 256
          },
          {
            "bearingDeg": 60,
            "lengthYd": 120
          }
        ]
      },
      {
        "hole": 18,
        "bearingDeg": 279,
        "par": 5,
        "lengthYd": 544
      }
    ]
  },
  {
    "key": "valley",
    "name": "Valley Golf Course",
    "aliases": [
      "valley golf",
      "valley"
    ],
    "holes": [
      {
        "hole": 1,
        "bearingDeg": 20,
        "par": 4,
        "lengthYd": 358
      },
      {
        "hole": 2,
        "bearingDeg": 83,
        "par": 3,
        "lengthYd": 165
      },
      {
        "hole": 3,
        "bearingDeg": 69,
        "par": 5,
        "lengthYd": 498
      },
      {
        "hole": 4,
        "bearingDeg": 274,
        "par": 4,
        "lengthYd": 405
      },
      {
        "hole": 5,
        "bearingDeg": 95,
        "par": 5,
        "lengthYd": 546
      },
      {
        "hole": 6,
        "bearingDeg": 217,
        "par": 4,
        "lengthYd": 387
      },
      {
        "hole": 7,
        "bearingDeg": 180,
        "par": 3,
        "lengthYd": 197
      },
      {
        "hole": 8,
        "bearingDeg": 323,
        "par": 4,
        "lengthYd": 330
      },
      {
        "hole": 9,
        "bearingDeg": 234,
        "par": 3,
        "lengthYd": 356
      }
    ]
  },
  {
    "key": "gf-country-club",
    "name": "Grand Forks Country Club",
    "aliases": [
      "grand forks country club",
      "gfcc"
    ],
    "holes": [
      {
        "hole": 1,
        "bearingDeg": 309,
        "par": 4,
        "lengthYd": 414
      },
      {
        "hole": 2,
        "bearingDeg": 151,
        "par": 4,
        "lengthYd": 369
      },
      {
        "hole": 3,
        "bearingDeg": 247,
        "par": 5,
        "lengthYd": 523,
        "segments": [
          {
            "bearingDeg": 216,
            "lengthYd": 256
          },
          {
            "bearingDeg": 276,
            "lengthYd": 267
          }
        ]
      },
      {
        "hole": 4,
        "bearingDeg": 3,
        "par": 4,
        "lengthYd": 409
      },
      {
        "hole": 5,
        "bearingDeg": 171,
        "par": 3,
        "lengthYd": 205
      },
      {
        "hole": 6,
        "bearingDeg": 20,
        "par": 5,
        "lengthYd": 541,
        "segments": [
          {
            "bearingDeg": 353,
            "lengthYd": 275
          },
          {
            "bearingDeg": 49,
            "lengthYd": 266
          }
        ]
      },
      {
        "hole": 7,
        "bearingDeg": 124,
        "par": 4,
        "lengthYd": 348,
        "segments": [
          {
            "bearingDeg": 112,
            "lengthYd": 218
          },
          {
            "bearingDeg": 144,
            "lengthYd": 130
          }
        ]
      },
      {
        "hole": 8,
        "bearingDeg": 28,
        "par": 3,
        "lengthYd": 157
      },
      {
        "hole": 9,
        "bearingDeg": 172,
        "par": 4,
        "lengthYd": 443,
        "segments": [
          {
            "bearingDeg": 182,
            "lengthYd": 298
          },
          {
            "bearingDeg": 152,
            "lengthYd": 145
          }
        ]
      },
      {
        "hole": 10,
        "bearingDeg": 317,
        "par": 4,
        "lengthYd": 400
      },
      {
        "hole": 11,
        "bearingDeg": 235,
        "par": 4,
        "lengthYd": 410,
        "segments": [
          {
            "bearingDeg": 254,
            "lengthYd": 272
          },
          {
            "bearingDeg": 194,
            "lengthYd": 138
          }
        ]
      },
      {
        "hole": 12,
        "bearingDeg": 8,
        "par": 3,
        "lengthYd": 184
      },
      {
        "hole": 13,
        "bearingDeg": 84,
        "par": 4,
        "lengthYd": 338,
        "segments": [
          {
            "bearingDeg": 75,
            "lengthYd": 221
          },
          {
            "bearingDeg": 100,
            "lengthYd": 117
          }
        ]
      },
      {
        "hole": 14,
        "bearingDeg": 98,
        "par": 5,
        "lengthYd": 521,
        "segments": [
          {
            "bearingDeg": 100,
            "lengthYd": 210
          },
          {
            "bearingDeg": 88,
            "lengthYd": 254
          },
          {
            "bearingDeg": 133,
            "lengthYd": 57
          }
        ]
      },
      {
        "hole": 15,
        "bearingDeg": 147,
        "par": 4,
        "lengthYd": 430
      },
      {
        "hole": 16,
        "bearingDeg": 340,
        "par": 3,
        "lengthYd": 165
      },
      {
        "hole": 17,
        "bearingDeg": 155,
        "par": 5,
        "lengthYd": 534,
        "segments": [
          {
            "bearingDeg": 165,
            "lengthYd": 300
          },
          {
            "bearingDeg": 142,
            "lengthYd": 234
          }
        ]
      },
      {
        "hole": 18,
        "bearingDeg": 297,
        "par": 4,
        "lengthYd": 451,
        "segments": [
          {
            "bearingDeg": 284,
            "lengthYd": 282
          },
          {
            "bearingDeg": 319,
            "lengthYd": 169
          }
        ]
      }
    ]
  },
  {
    "key": "minakwa",
    "name": "Minakwa Golf Course",
    "aliases": [
      "minakwa"
    ],
    "holes": [
      {
        "hole": 1,
        "bearingDeg": 5,
        "par": 4,
        "lengthYd": 264
      },
      {
        "hole": 2,
        "bearingDeg": 270,
        "par": 4,
        "lengthYd": 361
      },
      {
        "hole": 3,
        "bearingDeg": 94,
        "par": 4,
        "lengthYd": 305
      },
      {
        "hole": 4,
        "bearingDeg": 178,
        "par": 3,
        "lengthYd": 137
      },
      {
        "hole": 5,
        "bearingDeg": 317,
        "par": 4,
        "lengthYd": 339,
        "segments": [
          {
            "bearingDeg": 330,
            "lengthYd": 237
          },
          {
            "bearingDeg": 287,
            "lengthYd": 102
          }
        ]
      },
      {
        "hole": 6,
        "bearingDeg": 157,
        "par": 3,
        "lengthYd": 235
      },
      {
        "hole": 7,
        "bearingDeg": 344,
        "par": 4,
        "lengthYd": 330
      },
      {
        "hole": 8,
        "bearingDeg": 179,
        "par": 5,
        "lengthYd": 497
      },
      {
        "hole": 9,
        "bearingDeg": 65,
        "par": 4,
        "lengthYd": 449
      }
    ]
  },
  {
    "key": "mayville",
    "name": "Mayville Golf Club",
    "aliases": [
      "mayville"
    ],
    "holes": [
      {
        "hole": 1,
        "bearingDeg": 245,
        "par": 5,
        "lengthYd": 487,
        "segments": [
          {
            "bearingDeg": 236,
            "lengthYd": 313
          },
          {
            "bearingDeg": 259,
            "lengthYd": 173
          }
        ]
      },
      {
        "hole": 2,
        "bearingDeg": 63,
        "par": 4,
        "lengthYd": 346,
        "segments": [
          {
            "bearingDeg": 73,
            "lengthYd": 237
          },
          {
            "bearingDeg": 42,
            "lengthYd": 109
          }
        ]
      },
      {
        "hole": 3,
        "bearingDeg": 347,
        "par": 3,
        "lengthYd": 148
      },
      {
        "hole": 4,
        "bearingDeg": 355,
        "par": 4,
        "lengthYd": 357,
        "segments": [
          {
            "bearingDeg": 348,
            "lengthYd": 238
          },
          {
            "bearingDeg": 11,
            "lengthYd": 119
          }
        ]
      },
      {
        "hole": 5,
        "bearingDeg": 63,
        "par": 4,
        "lengthYd": 306,
        "segments": [
          {
            "bearingDeg": 53,
            "lengthYd": 181
          },
          {
            "bearingDeg": 77,
            "lengthYd": 126
          }
        ]
      },
      {
        "hole": 6,
        "bearingDeg": 197,
        "par": 5,
        "lengthYd": 495
      },
      {
        "hole": 7,
        "bearingDeg": 8,
        "par": 4,
        "lengthYd": 382
      },
      {
        "hole": 8,
        "bearingDeg": 184,
        "par": 4,
        "lengthYd": 346
      },
      {
        "hole": 9,
        "bearingDeg": 102,
        "par": 3,
        "lengthYd": 201
      }
    ]
  },
  {
    "key": "goose-river",
    "name": "Goose River Golf Club",
    "aliases": [
      "goose river"
    ],
    "holes": [
      {
        "hole": 1,
        "bearingDeg": 356,
        "par": 4,
        "lengthYd": 341,
        "segments": [
          {
            "bearingDeg": 3,
            "lengthYd": 217
          },
          {
            "bearingDeg": 345,
            "lengthYd": 124
          }
        ]
      },
      {
        "hole": 2,
        "bearingDeg": 359,
        "par": 4,
        "lengthYd": 390
      },
      {
        "hole": 3,
        "bearingDeg": 123,
        "par": 4,
        "lengthYd": 357
      },
      {
        "hole": 4,
        "bearingDeg": 279,
        "par": 3,
        "lengthYd": 176
      },
      {
        "hole": 5,
        "bearingDeg": 178,
        "par": 5,
        "lengthYd": 474
      },
      {
        "hole": 6,
        "bearingDeg": 273,
        "par": 3,
        "lengthYd": 205
      },
      {
        "hole": 7,
        "bearingDeg": 4,
        "par": 5,
        "lengthYd": 536
      },
      {
        "hole": 8,
        "bearingDeg": 182,
        "par": 4,
        "lengthYd": 420
      },
      {
        "hole": 9,
        "bearingDeg": 194,
        "par": 3,
        "lengthYd": 154
      }
    ]
  },
  {
    "key": "edgewood",
    "name": "Edgewood Golf Course",
    "aliases": [
      "edgewood"
    ],
    "holes": [
      {
        "hole": 1,
        "bearingDeg": 279,
        "par": 4,
        "lengthYd": 420,
        "segments": [
          {
            "bearingDeg": 270,
            "lengthYd": 276
          },
          {
            "bearingDeg": 297,
            "lengthYd": 144
          }
        ]
      },
      {
        "hole": 2,
        "bearingDeg": 200,
        "par": 4,
        "lengthYd": 360
      },
      {
        "hole": 3,
        "bearingDeg": 241,
        "par": 3,
        "lengthYd": 188
      },
      {
        "hole": 4,
        "bearingDeg": 26,
        "par": 5,
        "lengthYd": 499,
        "segments": [
          {
            "bearingDeg": 31,
            "lengthYd": 377
          },
          {
            "bearingDeg": 10,
            "lengthYd": 122
          }
        ]
      },
      {
        "hole": 5,
        "bearingDeg": 30,
        "par": 4,
        "lengthYd": 377,
        "segments": [
          {
            "bearingDeg": 22,
            "lengthYd": 275
          },
          {
            "bearingDeg": 52,
            "lengthYd": 102
          }
        ]
      },
      {
        "hole": 6,
        "bearingDeg": 115,
        "par": 4,
        "lengthYd": 389
      },
      {
        "hole": 7,
        "bearingDeg": 292,
        "par": 4,
        "lengthYd": 397
      },
      {
        "hole": 8,
        "bearingDeg": 62,
        "par": 3,
        "lengthYd": 186
      },
      {
        "hole": 9,
        "bearingDeg": 150,
        "par": 4,
        "lengthYd": 343,
        "segments": [
          {
            "bearingDeg": 145,
            "lengthYd": 280
          },
          {
            "bearingDeg": 174,
            "lengthYd": 63
          }
        ]
      },
      {
        "hole": 10,
        "bearingDeg": 31,
        "par": 4,
        "lengthYd": 407,
        "segments": [
          {
            "bearingDeg": 23,
            "lengthYd": 260
          },
          {
            "bearingDeg": 46,
            "lengthYd": 147
          }
        ]
      },
      {
        "hole": 11,
        "bearingDeg": 243,
        "par": 4,
        "lengthYd": 339,
        "segments": [
          {
            "bearingDeg": 236,
            "lengthYd": 236
          },
          {
            "bearingDeg": 259,
            "lengthYd": 103
          }
        ]
      },
      {
        "hole": 12,
        "bearingDeg": 282,
        "par": 3,
        "lengthYd": 145
      },
      {
        "hole": 13,
        "bearingDeg": 71,
        "par": 5,
        "lengthYd": 478,
        "segments": [
          {
            "bearingDeg": 84,
            "lengthYd": 323
          },
          {
            "bearingDeg": 44,
            "lengthYd": 155
          }
        ]
      },
      {
        "hole": 14,
        "bearingDeg": 207,
        "par": 4,
        "lengthYd": 391,
        "segments": [
          {
            "bearingDeg": 196,
            "lengthYd": 277
          },
          {
            "bearingDeg": 233,
            "lengthYd": 114
          }
        ]
      },
      {
        "hole": 15,
        "bearingDeg": 57,
        "par": 3,
        "lengthYd": 183
      },
      {
        "hole": 16,
        "bearingDeg": 131,
        "par": 5,
        "lengthYd": 526
      },
      {
        "hole": 17,
        "bearingDeg": 308,
        "par": 4,
        "lengthYd": 375,
        "segments": [
          {
            "bearingDeg": 311,
            "lengthYd": 318
          },
          {
            "bearingDeg": 295,
            "lengthYd": 57
          }
        ]
      },
      {
        "hole": 18,
        "bearingDeg": 253,
        "par": 4,
        "lengthYd": 375,
        "segments": [
          {
            "bearingDeg": 258,
            "lengthYd": 259
          },
          {
            "bearingDeg": 242,
            "lengthYd": 116
          }
        ]
      }
    ]
  },
  {
    "key": "sandhill",
    "name": "Sand Hill Golf Course",
    "aliases": [
      "sand hill",
      "sandhill",
      "fertile"
    ],
    "holes": [
      {
        "hole": 1,
        "bearingDeg": 300,
        "par": 5,
        "lengthYd": 480,
        "segments": [
          {
            "bearingDeg": 327,
            "lengthYd": 238
          },
          {
            "bearingDeg": 273,
            "lengthYd": 241
          }
        ]
      },
      {
        "hole": 2,
        "bearingDeg": 171,
        "par": 3,
        "lengthYd": 236
      },
      {
        "hole": 3,
        "bearingDeg": 320,
        "par": 4,
        "lengthYd": 332,
        "segments": [
          {
            "bearingDeg": 311,
            "lengthYd": 204
          },
          {
            "bearingDeg": 334,
            "lengthYd": 128
          }
        ]
      },
      {
        "hole": 4,
        "bearingDeg": 175,
        "par": 4,
        "lengthYd": 270,
        "segments": [
          {
            "bearingDeg": 148,
            "lengthYd": 57
          },
          {
            "bearingDeg": 188,
            "lengthYd": 94
          },
          {
            "bearingDeg": 177,
            "lengthYd": 120
          }
        ]
      },
      {
        "hole": 5,
        "bearingDeg": 74,
        "par": 5,
        "lengthYd": 446
      },
      {
        "hole": 6,
        "bearingDeg": 67,
        "par": 4,
        "lengthYd": 328,
        "segments": [
          {
            "bearingDeg": 24,
            "lengthYd": 182
          },
          {
            "bearingDeg": 125,
            "lengthYd": 147
          }
        ]
      },
      {
        "hole": 7,
        "bearingDeg": 158,
        "par": 3,
        "lengthYd": 148
      },
      {
        "hole": 8,
        "bearingDeg": 252,
        "par": 4,
        "lengthYd": 340
      },
      {
        "hole": 9,
        "bearingDeg": 75,
        "par": 4,
        "lengthYd": 398,
        "segments": [
          {
            "bearingDeg": 84,
            "lengthYd": 258
          },
          {
            "bearingDeg": 56,
            "lengthYd": 140
          }
        ]
      }
    ]
  }
];
